FROM circleci/php:7.2-apache-stretch-node-browsers

RUN sudo apt-get update \
    && sudo apt-get install -y libzip-dev zlib1g-dev libicu-dev g++ git \
    mysql-client mysql-server

RUN sudo docker-php-ext-install zip
RUN sudo docker-php-ext-configure intl
RUN sudo docker-php-ext-install intl
RUN sudo docker-php-ext-install pdo_mysql
RUN sudo docker-php-ext-install mysqli
RUN sudo pecl install grpc && sudo docker-php-ext-enable grpc
